name: Release

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Default
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'

    # - name: Pre Build
    #   run: |
    #     sudo apt-get update
    #     gem install bundler
    #     bundle install --jobs 4 --retry 3